dependencies:
  # - organization/repo@version
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'

networks:

  development:
    key_hash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000

  rinkeby:
    eth_usd_price_feed_address: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    link: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    vrf_coordinator: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    key_hash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
    verify: True
    
  mainnet-fork:
    eth_usd_price_feed_address: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419"

dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
